### PR TITLE
Check for const types

### LINKED ISSUE #40: Feature Request: Measure Type-Coverage for Class constants
PHP 8.3 and later support declaring a type for PHP Class constants.

It's one of the easier changes to enforce because you can partially do it with rector and it's easier to add manually because the values are, well, constant ;-)

Could we extend this package to allow to require a minimal type coverage for class consts?

### PR DESCRIPTION
**Pull request by pableu**
Fixes #40. 

My new code was heavily inspired by the implementation of the `property_type` rule.

### CODE REVIEW

**Comment by pableu** [comment]
@TomasVotruba I was not sure whether to call the new classes `...Constant...`, `...Const...`or `...ClassConst...`. I went for `Constant`. Do you have a preference?

**Comment by pableu** [comment]
@TomasVotruba What do you think? 🙃

**Comment by TomasVotruba** [comment]
Looks good to me :+1:  Thank for the features and making CI pass :muscle: 

Let's ship it :)

**Comment by pableu** [comment]
Very cool. Thank you!

**Pull request merged**
